// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLGqn3jbSaFSAWKvaqjQCT_qTiuHQmomY',
    appId: '1:609681700745:web:957396fb2fbbc2da9a5358',
    messagingSenderId: '609681700745',
    projectId: 'market-4fabd',
    authDomain: 'market-4fabd.firebaseapp.com',
    storageBucket: 'market-4fabd.appspot.com',
    measurementId: 'G-81RY506BPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJh6byuHi631qaF2aaPBK5JGOeU6VE1uA',
    appId: '1:609681700745:android:849a495fc4a95c6e9a5358',
    messagingSenderId: '609681700745',
    projectId: 'market-4fabd',
    storageBucket: 'market-4fabd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBgnFz0XbjsVDfMSsXhBQ3CUJW4za9KLs',
    appId: '1:609681700745:ios:0045cdca2f0218669a5358',
    messagingSenderId: '609681700745',
    projectId: 'market-4fabd',
    storageBucket: 'market-4fabd.appspot.com',
    iosClientId: '609681700745-0s303jr3g50qvnnkoutt3v3btvsvueg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.market',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBgnFz0XbjsVDfMSsXhBQ3CUJW4za9KLs',
    appId: '1:609681700745:ios:dcb17e436f6feee49a5358',
    messagingSenderId: '609681700745',
    projectId: 'market-4fabd',
    storageBucket: 'market-4fabd.appspot.com',
    iosClientId: '609681700745-l93lbno0hagmitncjm4ehdmstjp86jkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.market.RunnerTests',
  );
}
