name: fast_app_base
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #splash creator
  flutter_native_splash: ^2.3.0

  #dart
  meta: ^1.4.0
  quiver: ^3.2.1
  equatable: ^2.0.5

  #util
  velocity_x: ^4.1.0

  #data
  shared_preferences: ^2.0.15
  isar: 3.1.0
  isar_flutter_libs: 3.1.0

  #architecture
  event_bus: ^2.0.0
  get: ^4.6.5

  #ui - resource
  eva_icons_flutter: ^3.1.0
  google_fonts: ^4.0.4
  easy_localization: ^3.0.2
  flutter_cache_manager: ^3.3.0

  #ui - widget
  nav: ^1.3.9
  simple_shadow: ^0.3.1
  after_layout: ^1.2.0
  flutter_svg: ^2.0.3
  cached_network_image: ^3.2.3

  #ui - util
  keyboard_utils_fork: ^0.0.4

  #network
  dio: ^5.0.0
  retrofit: ^4.0.1
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  rive: ^0.11.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  retrofit_generator: '5.0.0'
  build_runner: '2.3.3'
  json_serializable: ^6.6.1
  isar_generator: 3.1.0
  mock_web_server: ^5.0.0-nullsafety.1
  flutter_oss_licenses: ^2.0.1
  test: ^1.22.0




flutter:

  uses-material-design: true
  assets:
    - assets/json/
    - assets/riv/
    - assets/image/
    - assets/image/icon/
    - assets/image/flag/
    - assets/image/darkmode/
    - assets/translations/
    - assets/



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700