// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpBVOWTDxWt3IIvT-dqzkuVEA3OrxHcOE',
    appId: '1:679619402677:web:22cae60bb327efa08857fc',
    messagingSenderId: '679619402677',
    projectId: 'realtime-quiz-app-3f226',
    authDomain: 'realtime-quiz-app-3f226.firebaseapp.com',
    databaseURL: 'https://realtime-quiz-app-3f226-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-quiz-app-3f226.appspot.com',
    measurementId: 'G-81JYR8VWWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8AqpSHcbX7c-HB-7LUljXl7_36crAX_0',
    appId: '1:679619402677:android:e8f38e05d0a955e28857fc',
    messagingSenderId: '679619402677',
    projectId: 'realtime-quiz-app-3f226',
    databaseURL: 'https://realtime-quiz-app-3f226-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-quiz-app-3f226.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAltREQnhiNFQHap_ptBolLeJUfvIt0yNo',
    appId: '1:679619402677:ios:f538a1311c0c04ad8857fc',
    messagingSenderId: '679619402677',
    projectId: 'realtime-quiz-app-3f226',
    databaseURL: 'https://realtime-quiz-app-3f226-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-quiz-app-3f226.appspot.com',
    iosBundleId: 'com.example.realtimeQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAltREQnhiNFQHap_ptBolLeJUfvIt0yNo',
    appId: '1:679619402677:ios:9b17e810e629aadb8857fc',
    messagingSenderId: '679619402677',
    projectId: 'realtime-quiz-app-3f226',
    databaseURL: 'https://realtime-quiz-app-3f226-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-quiz-app-3f226.appspot.com',
    iosBundleId: 'com.example.realtimeQuizApp.RunnerTests',
  );
}
