name: e_commerce_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bloc_concurrency: ^0.2.4
  dart_code_metrics: ^5.7.6
  dio: ^5.4.0
  flutter:
    sdk: flutter


  flutter_bloc: ^8.1.4
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.2.0
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  mocktail: ^1.0.3
  retrofit: ^4.1.0
  stream_transform: ^2.1.0
  intl: ^0.18.0
  lottie: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  bootpay: ^4.8.3
  kakao_flutter_sdk_user: ^1.8.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  shimmer: ^3.0.0
  flutter_dotenv: ^5.1.0
  firebase_crashlytics: ^3.4.14
  

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/icon/
    - assets/image/
    - assets/lottie/
    - assets/env/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700